### ISSUE TITLE
from utils import progress_bar

### ISSUE THREAD

**Issue by zwb170010** [MasLiang/Learning-without-Forgetting-using-Pytorch#1]
from utils import progress_bar

**Comment by zwb170010** [comment]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from utils import progress_bar
ModuleNotFoundError: No module named 'utils'

**Comment by MasLiang** [comment]
I'm so sorry that i didn't upload this file~But i don't have it now. I will upload it as soon as possible. And in fact it is just used to show the results beautifully.
