### ISSUE TITLE
NO FILE

### ISSUE THREAD

**Issue by Alex-arch** [MasLiang/Learning-without-Forgetting-using-Pytorch#8]
In dataset.py, no images.txt, image_class_labels.txt, train_test_split.txt, etc.

**Comment by MasLiang** [comment]
it is your datasets, plz check your path :)

**Comment by Alex-arch** [comment]
> it is your datasets, plz check your path :)

OK， i understand. Could you please provide these files so that i can run the code on CUB data set? I'm sorry to bother you again but i really don't know how to write these files?

**Comment by MagicHealer** [comment]
@Alex-arch Have you successfully run the code?
